module.exports.teams = ['bruins', 'sabres', 'devils', 'islanders', 'rangers',
  'flyers', 'penguins', 'capitals', 'hurricanes', 'blackhawks',
  'bluejackets', 'stars', 'redwings', 'panthers', 'predators',
  'lightning', 'ducks', 'coyotes', 'avalanche', 'kings',
  'wild', 'sharks', 'blues', 'goldenknights', 'flames', 'oilers',
  'canadiens', 'senators', 'mapleleafs', 'canucks', 'jets'
];
// module.exports.teams = ['capitals'
// ];

module.exports.teamMap = {
    "bruins": "Boston Bruins",
    "sabres": "Buffalo Sabres",
    "devils": "New Jersey Devils",
    "islanders": "New York Islanders",
    "rangers": "New York Rangers",
    "flyers": "Philadelphia Flyers",
    "penguins": "Pittsburgh Penguins",
    "capitals": "Washington Capitals",
    "hurricanes": "Carolina Hurricanes",
    "blackhawks": "Chicago Blackhawks",
    "bluejackets": "Columbus Blue Jackets",
    "stars": "Dallas Stars",
    "redwings": "Detroit Red Wings",
    "panthers": "Florida Panthers",
    "predators": "Nashville Predators",
    "lightning": "Tampa Bay Lightning",
    "ducks": "Anaheim Ducks",
    "coyotes": "Arizona Coyotes",
    "avalanche": "Colorado Avalanche",
    "kings": "Los Angeles Kings",
    "wild": "Minnesota Wild",
    "sharks": "San Jose Sharks",
    "blues": "St Louis Blues",
    "goldenknights": "Vegas Golden Knights",
    "flames": "Calgary Flames",
    "oilers": "Edmonton Oilers",
    "canadiens": "Montréal Canadiens",
    "senators": "Ottawa Senators",
    "mapleleafs": "Toronto Maple Leafs",
    "canucks": "Vancouver Canucks",
    "jets": "Winnipeg Jets"
}

module.exports.firstYearMap = {
  "bruins": "1924",
  "sabres": "1970",
  "devils": "1974",
  "islanders": "1972",
  "rangers": "1926",
  "flyers": "1967",
  "penguins": "1967",
  "capitals": "1974",
  "hurricanes": "1979",
  "blackhawks": "1926",
  "bluejackets": "2000",
  "stars": "1967",
  "redwings": "1926",
  "panthers": "1993",
  "predators": "1998",
  "lightning": "1992",
  "ducks": "1993",
  "coyotes": "1979",
  "avalanche": "1979",
  "kings": "1967",
  "wild": "2000",
  "sharks": "1991",
  "blues": "1967",
  "goldenknights": "2017",
  "flames": "1972",
  "oilers": "1979",
  "canadiens": "1917",
  "senators": "1992",
  "mapleleafs": "1917",
  "canucks": "1970",
  "jets": "1999"
}

// module.exports.teams = ['capitals'
// ];
